### PR TITLE
Japanese translations nebosuker

### PR DESCRIPTION
**Pull request by nebosuker**
Thank you for wonderful tool!!

I created Japanese language translation file.
I would be happy if you merge this for Japanese developers. Thank you.

_# I am new to this world of GitHub pull requests, so please forgive me if there is something wrong or rude._

### CODE REVIEW

**Comment by ivictbor** [comment]
@nebosuker thank you! Looks awesome!

**Comment by nebosuker** [comment]
Wow! I'm so excited I could help you. 
Thank you for pulling!

**Comment by nebosuker** [comment]
I found I put ja.lang.js in a wrong directory.
Please merge new pull request.  Sorry to bother you.

**Comment by ivictbor** [comment]
@nebosuker released, moved file, also added to translations config and readme

**Pull request merged**
